name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        run: echo "Using Checkstyle"

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Upload Checkstyle Result
        uses: actions/upload-artifact@v4
        with:
          path: target/reports/checkstyle.html
          overwrite: true

      - name: Run Maven Test
        run: mvn test

      - name: Jacoco Report
        uses: actions/upload-artifact@v4
        with:
          path: target/site/jacoco/index.html
          overwrite: true
